baseURL = '/'
languageCode = 'en-us'
theme = "nightfall"

[markup.goldmark.renderer]
  unsafe= true

[module]
[[module.mounts]]
  source = 'assets/images'
  target = 'assets/images'

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

[params]
author = "Samuel Wibrow"
description = "A blog written with AI"
user = "samuel"
hostname = "wibrow.net"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/swibrow"

[[params.social]]
key = 1
name = "instagram"
url = "https://www.instagram.com/swibrow/"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/samuelwibrow/"

[[params.social]]
key = 3
name = "email"
url = "mailto:sam.wibrow@gmail.com"
