baseURL = '/'
languageCode = 'en-us'
theme = "nightfall"

[markup.goldmark.renderer]
  unsafe= true

[module]
[[module.mounts]]
  source = 'assets/images'
  target = 'assets/images'

[menu]
  [[menu.header]]
    name = "posts"
    weight = 10
    url = "posts"
  [[menu.header]]
    name = "snippets"
    weight = 20
    url = "snippets"
  [[menu.header]]
    name = "projects"
    weight = 130
    url = "projects"
  [[menu.header]]
    name = "tools"
    weight = 140
    url = "tools"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"

[params]
user = "samuel"
hostname = "wibrow.net"
published = false
readingTime = false
tags = false
showMetadata = false
description = "A blog mostly written with LLMs"
footerHtml = ''
[params.author]
  name = "Samuel Wibrow"
  email = ""

[[params.social]]
key = 0
name = "github"
url = "https://github.com/swibrow"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/samuelwibrow/"

[[params.social]]
key = 4
name = "strava"
url = "https://www.strava.com/athletes/21868831"